name: On push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  checks: write

jobs:
  spdx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SPDX License Check
        uses: enarx/spdx@master
        with:
          licenses: Apache-2.0
